# sample dev block in the toml
# note: each of these fields are optional and should only be used if you need an override
[dev]
  command = "pnpm --filter astro run dev" # Command to start your dev server
  targetPort = 4321 # The port for your application server, framework, or site generator
  port = 8888 # The port that the Netlify Dev will be accessible on
